name: "Bug Report 🐞"
description: "Something is broken and you have a reliable reproduction? Let us know here"
title: "[BUG]: "
lables: ["bug", "needs triage"]
body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out this bug report!"
  - type: textarea
    id: description
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of what the bug is."
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: "Describe the bug"
      description: "Steps to reproduce the behavior:"
      value: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: "Expected behavior"
      description: "A clear and concise description of what you expected to happen."
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: "If applicable, add screenshots to help explain your problem."
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: "Environment"
      description: "Please complete the following information:"
      value: |
        - Library version: [e.g. 1.1.0]
        - Browser [e.g. chrome, safari]
        - Device: [e.g. MacBook Pro (M1)]
        - OS: [e.g. 13.0 (22A380)]
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: "Additional context"
      description: "Add any other context about the problem here."
      value: |
        - OS: [e.g. iOS]
        - Browser [e.g. chrome, safari]
        - Version [e.g. v1.1.0]
    validations:
      required: false
