name: "Bug Report 🐞"
description: "Something is broken and you have a reliable reproduction? Let us know here"
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out this bug report!"
  - type: textarea
    id: description
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of what the bug is."
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: "Steps to reproduce"
      description: "How can we find the bug?"
      value: |
        1. Go to '...'
        1. Click on '...'
        1. Scroll down to '...'
        1. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: "Expected behavior"
      description: "A clear and concise description of what you expected to happen."
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: "If applicable, add screenshots to help explain your problem."
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: "Environment"
      description: "Please complete the following information:"
      value: |
        | Area | Using |
        | -- | -- |
        | Library version | v1.1.0 |
        | Browser | Chrome |
        | Device | MacBook Pro (M1) |
        | OS | macOS 13.2.1 (22D68) |
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: "Additional context"
      description: "Add any other context about the problem here."
    validations:
      required: false
