export const iconNames = [
	'add-circle-outline',
	'add-circle',
	'add',
	'arrow-down',
	'arrow-left',
	'arrow-right',
	'arrow-up',
	'check-circle-outline',
	'check-circle',
	'check',
	'checkbox-false',
	'checkbox-true-outline',
	'checkbox-true',
	'chevron-down',
	'chevron-left',
	'chevron-right',
	'chevron-up',
	'close-circle-outline',
	'close-circle',
	'close',
	'collapse-left',
	'collapse-right',
	'expand-left',
	'expand-right',
	'hamburger',
	'plus',
] as const

export type IconName = typeof iconNames[number]
