name: CI + CD

on:
  push:
    branches: [ next ]
  pull_request:
    branches: [ next ]
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm ci
        
      - run: npm run build
      
  Lint:
    needs: [ Build ]
    runs-on: ubuntu-latest
    steps:
      - run: npm run lint
        
  DeployDev:
    name: Deploy to Dev
    if: github.event_name == 'pull_request'
    needs: [ Lint ]
    runs-on: ubuntu-latest
    environment:
      name: Development
      url: 'https://www.chromatic.com/builds?appId=63624c21a3dee89abb470279'
    steps:
      - name: Deploy
        run: npm run deploy:chromatic
        
  DeployStaging:
    name: Deploy to Staging
    if: github.event.ref == 'refs/heads/next'
    needs: [ Lint ]
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: 'https://test.my-library.com'
    steps:
      - name: Deploy
        run: npm run deploy:test
        
  DeployProd:
    name: Deploy to Production
    needs: [ DeployStaging ]
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: 'https://lib.casperdesign.no'
    steps:
      - name: Build
        run: npm run build:storybook
        
      - name: Deploy
        run: npm run deploy
