name: CI

on: [ push ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Cache Node Modules
      id: node-cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}
    
    - name: Install Dependencies
      if: steps.node-cache.outputs.cache-hit != 'true'
      run: npm ci
      
    - run: npm run lint
    
  build:
    name: Build
    needs: lint
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Cache Node Modules
      id: node-cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}
    
    - name: Install Dependencies
      if: steps.node-cache.outputs.cache-hit != 'true'
      run: npm ci
      
    - run: npm run build --if-present
      
  test:
    name: Test
    needs: [ lint, build ]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Cache Node Modules
      id: node-cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}
    
    - name: Install Dependencies
      if: steps.node-cache.outputs.cache-hit != 'true'
      run: npm ci
      
    - run: npm run test:ci
