name: Node CI

on: [ push ]

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
        
    - name: Node Setup
      uses: actions/setup-node@v3
    
    - name: Cache Node Modules
      id: node-cache
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          /home/runner/.cache/Cypress
        key: node-modules-${{ hashFiles('package-lock.json') }}
    
    - name: Install Dependencies
      if: steps.node-cache.outputs.cache-hit != 'true'
      run: npm ci
      
    - name: Lint
      run: npm run lint
      
    - name: Build
      run: npm run build --if-present
      
    - name: Test
      run: npm run test:ci
