name: CI

on:
  workflow_dispatch:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Cache Node Modules
      id: node-cache
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          /home/runner/.cache/Cypress
        key: node-modules-${{ hashFiles('package-lock.json') }}
    
    - name: Install Dependencies
      run: npm ci

  lint:
    name: Lint
    needs: setup
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Cache Node Modules
      id: node-cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}
      
    - run: npm run lint
    
  build:
    name: Build
    needs: setup
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Cache Node Modules
      id: node-cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}
      
    - run: npm run build --if-present
      
  test:
    name: Test
    needs: [ setup, build ]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Cache Node Modules
      id: node-cache
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          /home/runner/.cache/Cypress
        key: node-modules-${{ hashFiles('package-lock.json') }}
      
    - run: npm run test:ci
