name: Test workflow

on:
  workflow_dispatch:

jobs:
  setup:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Cache Node Modules
      id: node-cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: node-modules-cache
    
    - name: Install Dependencies
      if: steps.node-cache.outputs.cache-hit != 'true'
      run: npm i
      
  build:
  
    needs: setup
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/cache@v3
      with:
        key: node-modules-cache
        
    - run: npm run build
