name: Test workflow

on:
  workflow_dispatch:

jobs:
  setup:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Node setup
      run: npm ci
    
    - name: Upload node_modules
      uses: actions/upload-artifact@v3
      with:
        name: node_modules
        path: node_modules
  
  build:
  
    needs: setup
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Download node_modules
      uses: actions/download-artifact@v3
      with:
        name: node_modules
        
    - name: Build
      run: npm run build
